# https://taskfile.dev

version: '3'

tasks:
  default:
    deps:
      - task: lint
      - task: test
      - task: build
  install:
    cmds:
      - go install -ldflags "-X main.commit=$(git rev-parse HEAD)"
  build:preview:
    cmds:
      - goreleaser build --snapshot --single-target --clean --output dist/selfup
  build:
    cmds:
      - go build -o ./dist/selfup ./cmd/selfup
  run:
    cmds:
      - go run ./cmd/selfup {{.CLI_ARGS}}
  list:
    cmds:
      - go run ./cmd/selfup --prefix='# selfup ' --list-targets --skip-by='nix run' .github/workflows/*.yml
  update:
    cmds:
      - nix flake update --commit-lock-file
      - nix develop --command go run ./cmd/selfup --prefix='# selfup ' --skip-by='nix run' .github/workflows/*.yml
      - git commit -m 'Update CI dependencies with sync to nixpkgs' .github
  test:
    cmds:
      - go test ./...
  fmt:
    cmds:
      - typos . .github .vscode --write-changes
      - dprint fmt
      - go fmt ./...
      - nixpkgs-fmt ./*.nix
  lint:
    # go fmt does not have option for no effect - https://github.com/golang/go/issues/41189
    cmds:
      - dprint check
      - go vet ./...
      - goreleaser check
      - typos . .github .vscode
      - nixpkgs-fmt --check ./*.nix
      - staticcheck ./...
  deps:
    cmds:
      - nix --version
      - task --version
      - go version
      - dprint --version
      - goreleaser --version
      - typos --version
      - staticcheck --version
