name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          # This will be changed
          dprint-version: '0.39.0' # selfup { "extract": "\\d[^']+", "replacer": ["dprint", "--version"], "nth": 2 }

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      # This will not be changed
      - uses: crate-ci/typos@v1.10.9 # selfup { "extract": "\\d\\.\\d+\\.\\d+", "replacer": ["echo", "1.10.9"] }
        with:
          files: |
            .
            .github
            .vscode
