name: Lint

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  dprint:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
        with:
          # This will be changed
          dprint-version: '0.39.0' # selfup { "regex": "\\d[^']+", "script": "dprint --version | cut -d ' ' -f 2" }

  typos:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # This will not be changed
      - uses: crate-ci/typos@v1.10.9 # selfup { "regex": "\\d\\.\\d+\\.\\d+", "script": "echo 1.10.9" }
        with:
          files: |
            .
            .github
            .vscode
