name: GitHub API commit tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

env:
  # https://stackoverflow.com/a/71158878/1212807
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  # https://docs.github.com/ja/rest/git/commits?apiVersion=2022-11-28#create-a-commit
  # https://github.com/cli/cli/issues/10365
  commit:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install ghcp
        working-directory: ${{ runner.temp }}
        run: |
          curl -OL https://github.com/int128/ghcp/releases/download/v1.13.5/ghcp_linux_amd64.zip
          unzip ghcp_linux_amd64.zip
          mkdir --parents /home/runner/.ghcp/bin
          mv ghcp /home/runner/.ghcp/bin
          echo '/home/runner/.ghcp/bin' >> $GITHUB_PATH
      - name: Create diff
        run: |
          echo ':)' >> README.md
      - name: Commit
        env:
          GITHUB_TOKEN: '${{ github.token }}'
        run: |
          ghcp commit --repo '${{ github.repository }}' --branch '${{ env.BRANCH_NAME }}' --message 'Add testing commit with GitHub API' README.md
